export const STRINGS = {
  SAVE: 'Save',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  EDIT: 'Edit',
  CREATE: 'Create',
  UPDATE: 'Update',
  SUBMIT: 'Submit',
  CLOSE: 'Close',
  CONFIRM: 'Confirm',
  SEARCH: 'Search',
  FILTER: 'Filter',
  EXPORT: 'Export',
  IMPORT: 'Import',
  ADD_NEW: 'Add New',
  LOADING: 'Loading...',
  NO_DATA: 'No data available',
  ERROR_GENERIC: 'An error occurred. Please try again.',
  SUCCESS_GENERIC: 'Operation completed successfully.',
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  REQUIRED_FIELD: 'This field is required',
  INVALID_EMAIL: 'Please enter a valid email address',
  DELETE_CONFIRM: 'Are you sure you want to delete this item?',
};
